name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Gradle tasks
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v "$PWD":/project \
            -w /project \
            -e GRADLE_USER_HOME=/project/.gradle-home \
            gradle:jdk17 gradle clean build --no-daemon